### ISSUE TITLE
Change Orb Request

### ISSUE THREAD

**Issue by pije76** [Kibo/AstroChart#1]
I don't see the option to change the orb at settings.js

**Comment by Kibo** [comment]
Hi Pije
this graphics library does not calculate orbit. 

Please, see data:
`"aspects":[ [5,95,"#f00"], [20,140,"#f0f"], ... ]`

`"aspects":[ [POINT_IN_CIRCLE_1,POINT_IN_CIRCLE_2, COLOR], ...]`

This library only displays your data.

**Comment by Kibo** [comment]
The new version will be available soon. Now as the [DEV branch](https://github.com/Kibo/AstroChart/tree/dev).

**Comment by Kibo** [comment]
The feature has been added.
