### ISSUE TITLE
Libra symbol is confused with North Node symbol

### ISSUE THREAD

**Issue by choijongsoo** [Kibo/AstroChart#10]
Hi, I am very impressed by your job.
However, I have found Libra symbol is confused with North node symbol.
As far as I know, the symbol on the seventh sign should look like this: ♎. 
Thank you for your good job!

**Comment by damirmur** [comment]
Greetings.
Change the Scale function to the one below.
In astroshart.js, it starts with line 999.
`	function libra( x, y ){
		
		// center symbol
		var xShift = 0; //px						
		var yShift = 0; //px		
		x =  Math.round(x + (xShift * astrology.SYMBOL_SCALE));
		y =  Math.round(y + (yShift * astrology.SYMBOL_SCALE));
                console.log(x,y);
		
		var wrapper = document.createElementNS(context.root.namespaceURI, "g");
		wrapper.setAttribute("transform", "translate(" + ( -x * (astrology.SYMBOL_SCALE - 1)) + "," + (-y * (astrology.SYMBOL_SCALE - 1)) + ") scale(" + astrology.SYMBOL_SCALE + ")");
				
			var node = document.createElementNS( context.root.namespaceURI, "path");
        		node.setAttribute("d", "m " + x+", " +y+ "  0 0c0-.271.01-.802.031-1.594 1.292-.583 1.938-1.562 1.938-2.937 0-.896-.312-1.635-.937-2.219-.604-.604-1.344-.906-2.219-.906-.896 0-1.635.302-2.219.906-.625.604-.937 1.354-.937 2.25 0 1.333.656 2.292 1.969 2.875l0 1.625-7.719 0 0-1.531c.875 0 2.625-.01 5.25-.031-.687-1-1.031-1.979-1.031-2.937 0-1.312.458-2.427 1.375-3.344s2.021-1.375 3.312-1.375c1.313 0 2.427.458 3.344 1.375.896 .917 1.344 2.031 1.344 3.344 0 .979-.333 1.969-1 2.969l5.25 0 0 1.531-7.75 0zm-10.094 4 0-1.562 17.844 0 0 1.563-17.844 0z");
			node.setAttribute("stroke", astrology.SIGNS_COLOR);		 
			node.setAttribute("stroke-width", astrology.SIGNS_STROKE);			
			node.setAttribute("fill", "none");												
			wrapper.appendChild(node);
											
		return wrapper;
	};
`

**Comment by 0xStarcat** [comment]
Would you be able to make a PR with this correction?

**Comment by damirmur** [comment]
> Сможете ли вы устроить пиар с этой поправкой?

Pull requests? I don't see the point. The author probably will not develop this module, he is not an astrologer. I wrote mine, with its own input. Look here [a link] (https://github.com/damirmur/AstroChartSVG)

**Comment by 0xStarcat** [comment]
thanks!

**Comment by Kibo** [comment]
Fixed.
