### ISSUE TITLE
Synastry Chart Support

### ISSUE THREAD

**Issue by viniciusfss** [Kibo/AstroChart#11]
Hi,

Kibo, first of all, great job with these astrology projects, the code and the documentation. It is everything very well structured.

I have a demand of creating a Synastry chart, and I'd like to use your project as a starting point. Could you give any directions on where to start? 

My intention is to make it open source afterwards as well, and your help would be very welcome.

Thanks in advance.

**Comment by Kibo** [comment]
Hi,

thanks for your message.

> "I have a demand of creating a Synastry chart"

In general there are **two view** in AstroChart.
The first is called "Radix", but in general, it is the view of planets **in the circle**.
The second called "Transit" is the view **outside the circle**.

With these two views you can make any astrology chart. For example Synastry, Secondary Progression, Solar ...

The chart shows **your data**. What the data mean and how you name the chart is not significant for the chart.


Regards
