### ISSUE TITLE
Remove the transit cusps/houses

### ISSUE THREAD

**Issue by devitsurge** [Kibo/AstroChart#23]
Hi,

thanks for the amazing job here.

This is probably not an issue but I don't think the transit cusps are necesary and are more noisy than helpful. How can I remove them so I only have the transit planets on the outer layer?

![image](https://user-images.githubusercontent.com/61391043/93536616-0f047f00-f90f-11ea-8e46-028d288581fb.png)

Thanks again.

**Comment by Kibo** [comment]
Hi friend
https://github.com/Kibo/AstroChart/blob/master/project/src/chart.js#L49
