### ISSUE TITLE
Why houses are path and not text?

### ISSUE THREAD

**Issue by afucher** [Kibo/AstroChart#30]
I would like to know if there is any reason for houses number to be svg path and not text with the numbers.

**Comment by Kibo** [comment]
Hi Arthur

I was planning to cut the graph into wood ( CNC ). For this reason I need
curves, not TTF font.
That is why I used the "stroke only
<https://cdn.rawgit.com/Kibo/AstroChart/master/project/examples/transit/stroke_only.html>"
graph too.

Tom
