### ISSUE TITLE
Can't change the background color of signs.

### ISSUE THREAD

**Issue by EsoCoding** [Kibo/AstroChart#32]
Hi,  

i am struggling with the settings, i can change most settings. But if i try to change background color of the signs, nothing happens. 

```
var settings = { COLOR_TAURUS:"#fff" };
var radix = new astrology.Chart('wheel', 600, 600, settings).radix( data );
```

Other options like `SIGNS_COLOR` seem to work, but the sign colors don't...

**Comment by afucher** [comment]
Hi @HermesTrismegistus , thanks for reporting this.
I found the issue, and I'll work on fix it.

As a workaround you can use the `COLORS_SIGNS` setting property, you need to set all the colors. 
Here is an example changing the aries color:
``` var settings = {COLORS_SIGNS: ["#FF0000", astrology.COLOR_TAURUS, astrology.COLOR_GEMINI, astrology.COLOR_CANCER, astrology.COLOR_LEO, astrology.COLOR_VIRGO, astrology.COLOR_LIBRA, astrology.COLOR_SCORPIO, astrology.COLOR_SAGITTARIUS, astrology.COLOR_CAPRICORN, astrology.COLOR_AQUARIUS, astrology.COLOR_PISCES]};```
