### ISSUE TITLE
Maximum call stack size exceeded 

### ISSUE THREAD

**Issue by Kibo** [Kibo/AstroChart#5]
When searching for collisions of planets in the method _astrology.utils.assemble_ may occur _maximum call stack size exceeded_.

The method is called recursively and under unfulfilled conditions (COLLISION_RADIUS X SCALE X paper size ) can terminated by stack size exceeded.

Behavior can be affected by setting the value:

- astrology.COLLISION_RADIUS
- astrology.SYMBOL_SCALE
- paper size

@see
https://github.com/Kibo/AstroChart/issues/3

However, the error condition must be catch.

**Comment by cptolemy** [comment]
Hi,

Shall I give you the code to test? It's actually equal to yours. The only difference is the data used in Radix and Transit.

Kind regards

Kepler

**Comment by Kibo** [comment]
> Shall I give you the code to test? The only difference is the data used in Radix and Transit.

If possible to send the data to test, I fix the bug and verify that the problem is not already there. But it is not absolutely necessary.

Thanks
