### ISSUE TITLE
Libra sign

### ISSUE THREAD

**Issue by cptolemy** [Kibo/AstroChart#6]
Good afternoon,

Is it possible to turn the Libra (balance) sign in the zodiac more like the original symbol instead of looking like the ascending node?

Cheers,

Ptolemy

**Comment by damirmur** [comment]
Greetings.
Change the Scale function to the one below.
In astroshart.js, it starts with line 999.
`	function libra( x, y ){
		
		// center symbol
		var xShift = 0; //px						
		var yShift = 0; //px		
		x =  Math.round(x + (xShift * astrology.SYMBOL_SCALE));
		y =  Math.round(y + (yShift * astrology.SYMBOL_SCALE));
                console.log(x,y);
		
		var wrapper = document.createElementNS(context.root.namespaceURI, "g");
		wrapper.setAttribute("transform", "translate(" + ( -x * (astrology.SYMBOL_SCALE - 1)) + "," + (-y * (astrology.SYMBOL_SCALE - 1)) + ") scale(" + astrology.SYMBOL_SCALE + ")");
				
			var node = document.createElementNS( context.root.namespaceURI, "path");
        		node.setAttribute("d", "m " + x+", " +y+ "  0 0c0-.271.01-.802.031-1.594 1.292-.583 1.938-1.562 1.938-2.937 0-.896-.312-1.635-.937-2.219-.604-.604-1.344-.906-2.219-.906-.896 0-1.635.302-2.219.906-.625.604-.937 1.354-.937 2.25 0 1.333.656 2.292 1.969 2.875l0 1.625-7.719 0 0-1.531c.875 0 2.625-.01 5.25-.031-.687-1-1.031-1.979-1.031-2.937 0-1.312.458-2.427 1.375-3.344s2.021-1.375 3.312-1.375c1.313 0 2.427.458 3.344 1.375.896 .917 1.344 2.031 1.344 3.344 0 .979-.333 1.969-1 2.969l5.25 0 0 1.531-7.75 0zm-10.094 4 0-1.562 17.844 0 0 1.563-17.844 0z");
			node.setAttribute("stroke", astrology.SIGNS_COLOR);		 
			node.setAttribute("stroke-width", astrology.SIGNS_STROKE);			
			node.setAttribute("fill", "none");												
			wrapper.appendChild(node);
											
		return wrapper;
	};
`

**Comment by cptolemy** [comment]
Greetings

Thank you so much for the help. Actually, I had figured it out for some time, and I should have posted here the code for others to use it. My bad, and I'm sorry.

Kind regards

**Comment by damirmur** [comment]
Greetings. What have you improved, if not a secret, so as not to do double work?

**Comment by Kibo** [comment]
Done.

**Comment by Hamza4144** [comment]
hey, how are you can you please tell me how to add apollon symbol because its getting too big
