### ISSUE TITLE
New symbol - simple help

### ISSUE THREAD

**Issue by cptolemy** [Kibo/AstroChart#7]
Greatings

I'm creating a new simbol for the chart library. Can you please tell me in which units should I create it (px, mm, or etc.), with what size, and in which program (CorelDraw, Inkscape,etc) so they can be compatible to your own?

Kind regards

CPtolemy

**Comment by Kibo** [comment]
Hi 
there are some symbols in:
https://github.com/Kibo/AstroChart/tree/master/assets

I used Inscape for edit.

See for example:
https://github.com/Kibo/AstroChart/blob/master/project/src/svg.js#L293

You have to center the symbol. You can use calibration fot it:
https://github.com/Kibo/AstroChart/tree/master/project/examples/debug

Regards

**Comment by cptolemy** [comment]
Hi

Thanks for the reply. Those are good examples. Can you just please tell me, in Inkspace, if you were to create another symbol, in pixels let's say, would you use as origin (0,0) and what would be the width and height of the object - in pixels (or mm..)?

I've created a sample symbol, but it's either too big or goes out of the place.

My problem is actually there in Inkspace.

Sorry for the trouble.

Kind regards

**Comment by Kibo** [comment]
Hi

there is XML editor in Inkscape. You can see and edit SVG markup in it. 
The size of symbol you need estimate according to other symbol.

Sometimes there is _scale_ wraper (or atribute) in SVG markup in Inkscape. You have to remove it, to see the real size of symbol.

Regards

**Comment by Kibo** [comment]
The origin of symbol set as you need in Inkscape. Then you align in code:

For example
https://github.com/Kibo/AstroChart/blob/master/project/src/svg.js#L416
```
// center symbol
var xShift = -5; //px						
var yShift = -7; //px	
```

**Comment by cptolemy** [comment]
Hi Kibo

Thanks for the help :) Take care.

Kind regards

Ptolemy
