### ISSUE TITLE
Vertex

### ISSUE THREAD

**Issue by cptolemy** [Kibo/AstroChart#8]
Good morning Kibo

I am trying to add the Vertex point also in the chart - like the As, Dc, Ic, and MC. I got a red dot with a line at the right position....

I made the following changes to the code. I added the var

`astrology.SYMBOL_VX = "Vx";`

In the 

astrology.Radix.prototype.drawAxis = function(){

function, I coded:

`var VX = 12;
...
[AS,IC,DC,MC,VX].forEach( function(i) {`

There, if i==12, I made

`startPosition = astrology.utils.getPointPosition( this.cx, this.cy, this.radius, this.data.planets['Vertex'] + this.shift);
endPosition = astrology.utils.getPointPosition( this.cx, this.cy, axisRadius, this.data.planets['Vertex'] + this.shift);`

As you can see, I've passed the Vertex as if it was a planet.

And finnaly added - in the same function:

`if(i == VX){ 
textPosition = astrology.utils.getPointPosition( this.cx, this.cy, axisRadius + (10 * astrology.SYMBOL_SCALE), this.data.planets['Vertex'] - 2 + this.shift);
wrapper.appendChild( this.paper.getSymbol( astrology.SYMBOL_VX, textPosition.x, textPosition.y));
}`

Can you please help?

Kind regards

**Comment by Kibo** [comment]
Hi Ptolemy

add a new symbol to:
https://github.com/Kibo/AstroChart/blob/master/project/src/svg.js#L46

and then you can use it in data:
`"planets":{"Moon":[0], "Sun":[30], "Mercury":[60], ... "Vx":[123], ... },`

Regards
Tomas
