### ISSUE TITLE
Data description

### ISSUE THREAD

**Issue by ConstantineGochev** [Kibo/AstroChart#9]
Hello,

Very nicely written code. Can you give a little more detailed description of
the type of expected data. Is it the longitude and latitude of the given planet or 
something else... ? And also the same question for the cusps array.
Thank you for the effort tho.

Best regards,
Constantin

**Comment by Kibo** [comment]
Hello

there are positions in degrees on the circle. <0 - 360°)

Please, see examples code.

Regards
Tomas
